In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("../data/raw_traffic.csv")
df = pd.DataFrame(data)
df

                  DateTime  Junction  Vehicles           ID
0      2015-11-01 00:00:00         1        15  20151101001
1      2015-11-01 01:00:00         1        13  20151101011
2      2015-11-01 02:00:00         1        10  20151101021
3      2015-11-01 03:00:00         1         7  20151101031
4      2015-11-01 04:00:00         1         9  20151101041
...                    ...       ...       ...          ...
48115  2017-06-30 19:00:00         4        11  20170630194
48116  2017-06-30 20:00:00         4        30  20170630204
48117  2017-06-30 21:00:00         4        16  20170630214
48118  2017-06-30 22:00:00         4        22  20170630224
48119  2017-06-30 23:00:00         4        12  20170630234

[48120 rows x 4 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DateTime  48120 non-null  object
 1   Junction  48120 non-null  int64
 2   Vehicles  48120 non-null  int64
 3   ID        48120 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [4]:
df.describe()

           Junction      Vehicles            ID
count  48120.000000  48120.000000  4.812000e+04
mean       2.180549     22.791334  2.016330e+10
std        0.966955     20.750063  5.944854e+06
min        1.000000      1.000000  2.015110e+10
25%        1.000000      9.000000  2.016042e+10
50%        2.000000     15.000000  2.016093e+10
75%        3.000000     29.000000  2.017023e+10
max        4.000000    180.000000  2.017063e+10

In [5]:
print(df.isnull().sum())
data.drop_duplicates(inplace=True)

DateTime    0
Junction    0
Vehicles    0
ID          0
dtype: int64

In [6]:
df["DateTime"] = pd.to_datetime(df["DateTime"])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48120 entries, 0 to 48119
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DateTime  48120 non-null  datetime64[ns]
 1   Junction  48120 non-null  int64
 2   Vehicles  48120 non-null  int64
 3   ID        48120 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 1.5 MB

In [8]:
df["Hour"] = df["DateTime"].dt.hour
df["Month"] = df["DateTime"].dt.month
df["Day"] = df["DateTime"].dt.day
df["Weekday"] = df["DateTime"].dt.weekday

In [9]:
df.head()

,DateTime,Junction,Vehicles,ID,Hour,Month,Day,Weekday
0,2015-11-01 00:00:00,1,15,20151101001,0,11,1,6
1,2015-11-01 01:00:00,1,13,20151101011,1,11,1,6
2,2015-11-01 02:00:00,1,10,20151101021,2,11,1,6
3,2015-11-01 03:00:00,1,7,20151101031,3,11,1,6
4,2015-11-01 04:00:00,1,9,20151101041,4,11,1,6

In [10]:
df.to_csv("clean_traffic.csv", index=False)
print("A clean CSV is present in the data folder.")

A clean CSV is present in the data folder.