In [22]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib

In [23]:
data = pd.read_csv("../data/clean_traffic.csv")
df = pd.DataFrame(data)
df

,DateTime,Junction,Vehicles,ID,Hour,Month,Day,Weekday
0,2015-11-01 00:00:00,1,15,20151101001,0,11,1,6
1,2015-11-01 01:00:00,1,13,20151101011,1,11,1,6
2,2015-11-01 02:00:00,1,10,20151101021,2,11,1,6
3,2015-11-01 03:00:00,1,7,20151101031,3,11,1,6
4,2015-11-01 04:00:00,1,9,20151101041,4,11,1,6
...,...,...,...,...,...,...,...,...
48115,2017-06-30 19:00:00,4,11,20170630194,19,6,30,4
48116,2017-06-30 20:00:00,4,30,20170630204,20,6,30,4
48117,2017-06-30 21:00:00,4,16,20170630214,21,6,30,4
48118,2017-06-30 22:00:00,4,22,20170630224,22,6,30,4
48119,2017-06-30 23:00:00,4,12,20170630234,23,6,30,4

In [24]:
df["DateTime"] = pd.to_datetime(df["DateTime"])
df['Hour'] = df['DateTime'].dt.hour
df['Day'] = df['DateTime'].dt.day
df['Month'] = df['DateTime'].dt.month
df['Weekday'] = df['DateTime'].dt.weekday

In [25]:
df = df.sort_values(by=['Junction', 'DateTime'])

In [26]:
df['Lag_1'] = df.groupby('Junction')['Vehicles'].shift(1)
df['Lag_2'] = df.groupby('Junction')['Vehicles'].shift(2)
df['Lag_3'] = df.groupby('Junction')['Vehicles'].shift(3)

In [27]:
df['Rolling_Mean_3'] = (
    df.groupby('Junction')['Vehicles']
    .rolling(window=3)
    .mean()
    .reset_index(0, drop=True)
)

In [28]:
df.columns

Index(['DateTime', 'Junction', 'Vehicles', 'ID', 'Hour', 'Month', 'Day',
       'Weekday', 'Lag_1', 'Lag_2', 'Lag_3', 'Rolling_Mean_3'],
      dtype='str')

In [29]:
features = [
    'Junction',
    'Hour',
    'Day',
    'Month',
    'Weekday',
    'Lag_1',
    'Lag_2',
    'Lag_3',
    'Rolling_Mean_3'
]
X = df[features]
y = df['Vehicles']

In [30]:
split_index = int(len(X) * 0.8)

X_train = X[:split_index]
X_test = X[split_index:]

y_train = y[:split_index]
y_test = y[split_index:]

In [31]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [32]:
predictions = model.predict(X_test)

In [33]:
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

In [34]:
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

Mean Absolute Error: 0.43
Mean Squared Error: 3.50
R² Score: 0.96

In [35]:
results = pd.DataFrame({
    "Actual" : y_test,
    "Predicted" : predictions
})
results.head()

       Actual  Predicted
38496      17      16.89
38497      12      11.80
38498      10       9.73
38499       7       6.92
38500       4       4.39

In [36]:
feature_importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

feature_importance.sort_values(
    by='Importance',
    ascending=False
)

          Feature  Importance
8  Rolling_Mean_3    0.973615
6           Lag_2    0.013476
1            Hour    0.006116
5           Lag_1    0.004657
7           Lag_3    0.000870
2             Day    0.000355
0        Junction    0.000353
3           Month    0.000315
4         Weekday    0.000243

In [37]:
joblib.dump(
    model, "../models/traffic_model.pkl"
)

print("Model saved successfully 🚀")

Model saved successfully 🚀